name: CI
on: 
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

jobs:
  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build (shared lib)
        run: |
          cmake -B build-shared -DBUILD_SHARED_LIBS=TRUE
          cmake --build build-shared
      - name: Build (static lib)
        run: |
          cmake -B build-static
          cmake --build build-static
